server:
  port: 8082

spring:
  application:
    name: userinfo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/userinfo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234


  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: create


  data:
    rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 10


  jackson:
    serialization:
      fail-on-empty-beans: false
eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/