server:
  port: 8000

spring:
  main:
    web-application-type: reactive
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: userinfo
          uri: http://localhost:8080/
          predicates:
            - Path=/api/users/**

        - id: pharmacyservice
          uri: http://localhost:8081/
          predicates:
            -Path=/api/pharmacy/**

        - id: productservice
          uri: http://localhost:8082/
          predicates:
           -Path=/api/product/**
