server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  main:
    web-application-type: reactive
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: userinfo
          uri: http://localhost:8080/
          predicates:
            - Path=/api/users/**

        - id: pharmacyservice
          uri: http://localhost:8081/
          predicates:
            - Path=/api/pharmacy/**

        - id: productservice
          uri: http://localhost:8082/
          predicates:
           - Path=/api/products/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods: "*"


